baseurl                 = "https://abraham.red/"               # Your domain name. Must end with "/"
languageCode            = "en-us"
title                   = "Rajiv Abraham Nela"
theme                   = "hugo-theme-sam"
# googleAnalytics       = "UA-112438396-3"             # Tracking code, eg. "UA-111111111-1"

[params]
    dateform            = "Mon Jan 02, 2006"
    dateformfull        = "Mon Jan 2 2006 15:04:05 EST"
    favicon             = "/RajivAbrahamNela.jpg"
    pygmentsStyle       = "monokai"                     # https://help.farbox.com/pygments.html
    pygmentsCodefences  = true
    homepage            = "Home"                        # What to call the home page link
    galleryFolder       = "static/images"                     # Where you've put your images, after "/content/gallery/"
    clickablePhotos     = true                          # Allow links to the full size images
    footerText          = "Rajiv Abraham Nela is a Christian, Investor, Audiophile, Foodie, Shutterbug, Geek, and Traveler."

# Metadata
    description         = "Rajiv Abraham Nela is a Christian, Investor, Audiophile, Foodie, Shutterbug, Geek, and Traveler."            # Max 160 characters show in search results
    twitterCard         = "summary_large_image"         # Card value “summary”, “summary_large_image”, “app”, or “player”
    primaryImage        = "/RajivAbrahamNela.jpg"                     # Image that shows on Twitter cards and OpenGraph links


[[params.mainMenu]]
    link = "/about"
    text = "About"

[[params.mainMenu]]
    link = "/now"
    text = "Now"

[[params.mainMenu]]
    link = "/elsewhere"
    text = "Elsewhere"

[[params.mainMenu]]
    link = "/contact"
    text = "Contact"
    
[blackfriday] hrefTargetBlank = true