# Site settings
baseURL = "https://abraham.red/"
languageCode = "en-US"
title = "Rajiv Abraham Nela"
theme = "hugo-split-theme"
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT"]
[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true

# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-112438396-3"

# Copyright
copyright = "&copy;2018 Rajiv Abraham Nela"

[params]

  # Metadata for search engines and social sharing
  name = "Rajiv Abraham Nela"
  description = "Rajiv Abraham Nela is a Christian, audiophile, foodie, shutterbug, geek, and occasional blogger, though he's trying to change that last bit."
  shareImage = "http://res.cloudinary.com/abraham/image/upload/q_100/v1526951769/Abraham.jpg"
  twitterHandle = "unoabraham"

  # Favicon
  favicon = "http://res.cloudinary.com/abraham/image/upload/q_100/v1526951769/Abraham.jpg"

  # Section - Content
  [params.content]
    name = "Rajiv Abraham Nela"
    tagline = "Christian. Audiophile. Geek."
    bio = "Rajiv Abraham Nela is a Christian, audiophile, foodie, shutterbug, geek, and occasional blogger, though he's trying to change that last bit."

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "http://res.cloudinary.com/abraham/image/upload/q_100/v1526951769/Abraham.jpg"
      position = "center center"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = "videos/background.mp4"
      # youtubeId = "dk9uNWPP7EA"

  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Connect"

      [[params.links.list1.link]]
        text = "Microblogger"
        url = "https://abraham.uno/"

      [[params.links.list1.link]]
        text = "Photoblogger"
        url = "https://abraham.gallery/"
      
      [[params.links.list1.link]]
        text = "Indieblogger"
        url = "https://abraham.onl/"

      [[params.links.list1.link]]
        text = "Linkblogger"
        url = "https://abraham.link/"
         
      [[params.links.list1.link]]
        text = ""
        url = ""
      
  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Social"

      [[params.links.list2.link]]
        text = "Facebook"
        url = "https://www.facebook.com/939abraham"

      [[params.links.list2.link]]
        text = "Twitter"
        url = "https://twitter.com/unoabraham"

      [[params.links.list2.link]]
        text = "Mastodon"
        url = "https://mastodon.social/@unoabraham"

  # Links List #3
  [[params.links]]
    [params.links.list3]
      heading = "Personal"
                
      [[params.links.list3.link]]
        text = "Family Tree"
        url = "https://nela.in/"

      [[params.links.list3.link]]
        text = "Journal"
        url = "https://abraham.life/"

      [[params.links.list3.link]]
        text = "Email"
        url = "mailto:a@brah.am"

      #[[params.links.list3.link]]
       # text = "Call 939ABRAHAM"
       # url = ""

  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split